name: food_travel
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^7.3.0
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  flutter_clean_architecture: ^3.0.2
  flutter_facebook_login: ^3.0.0
  modal_progress_hud: ^0.1.3
  country_code_picker: ^1.3.12+1
  flutter_country_picker: ^0.1.6
  pin_input_text_field: ^3.0.1
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.2
  language_pickers: ^0.2.0+1
  smooth_star_rating: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true